# Generated by Django 3.1.3 on 2021-04-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teprunner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.IntegerField(verbose_name='计划id')),
                ('case_id', models.IntegerField(verbose_name='用例id')),
                ('result', models.CharField(max_length=50, verbose_name='运行结果')),
                ('elapsed', models.CharField(max_length=50, verbose_name='耗时')),
                ('output', models.TextField(default='', verbose_name='输出日志')),
                ('run_env', models.CharField(max_length=20, verbose_name='运行环境')),
                ('run_user_nickname', models.CharField(max_length=64, verbose_name='运行用户昵称')),
                ('run_time', models.DateTimeField(auto_now=True, verbose_name='运行时间')),
            ],
            options={
                'db_table': 'plan_result',
            },
        ),
        migrations.AlterField(
            model_name='plancase',
            name='plan_id',
            field=models.IntegerField(verbose_name='测试计划id'),
        ),
    ]
