# Generated by Django 3.1.3 on 2023-07-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teprunner', '0003_auto_20230718_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskresult',
            name='case_id',
        ),
    ]
